Repository Ashutosh1069/c-questions, pull requests merged in 2022-10, with the labels that each got.

#10 this is fourth
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted

#11 new filr
  rem.txt
Labels: hacktober-accepted, hacktoberfest-accepted

#12 Update README.md
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#13 Create Hello world.c
  Hello world.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#14 Create add_two_number.c
  add_two_number.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#17 updation
  BinarySearch.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#18 Error in header file
  Hello world.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#21 hi
  rem.txt
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#19 Just Made It More User Friendly
  add_two_number.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#20 Random
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#24 remark
  add_two_number.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#25 Hey
  rem.txt
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#23 Random
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#26 space
  BinarySearch.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#22 Updated
  Hello world.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#27 Create stack.c
  stack.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#32 hola
  rem.txt
Labels: hacktoberfest-accepted, hacktoberfest2022

#30 added number 3
  add_two_number.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#28 minor
  Hello world.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#29 updation
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#31 added a statement
  stack.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#36 Updated
  Hello world.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#35 space
  stack.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#33 space
  BinarySearch.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022

#37 Created MergeSort.c for Hacktoberfest
  MergeSort.c
Labels: hacktober-accepted, hacktoberfest-accepted, hacktoberfest2022
